### PR TITLE
Update zk library to use our fork.

### PR DESCRIPTION
**Pull request by claygoddard**
Use our fork for now to fix some session lost issues.
Additionally, update import package to reference new package name.

### CODE REVIEW

**Comment by claygoddard** [comment]
Need to do this first so that the packages match up when I update our internal repo.

**Comment by donjaime** [comment]
Seems reasonable. But I will defer to Jh and Scottb.

**Review by dragonsinth — APPROVED** [review]
LGTM, but why not just reference `fullstorydev/zk` in code instead of using a replace directive?  Until we can get a patch landed https://github.com/go-zookeeper/zk/pull/34 -- and there doesn't seem to be much interest in it :( -- this lib won't work with any other version of zk.

**Comment by claygoddard** [comment]
> LGTM, but why not just reference `fullstorydev/zk` in code instead of using a replace directive? Until we can get a patch landed [go-zookeeper/zk#34](https://github.com/go-zookeeper/zk/pull/34) -- and there doesn't seem to be much interest in it :( -- this lib won't work with any other version of zk.

That's fair. Was doing it for clarity, but I'll just point directly.

**Pull request merged**
